config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  
  resources :items

  devise_for :users

  resources :carts
  resources :users
  resources :orders
  resources :cart_items, only: [:create, :destroy]


  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end

  get 'team', to: 'static_pages#team'
  get 'uglycats', to: 'static_pages#uglycats'
  get 'fatcats', to:  'static_pages#fatcats'
  get 'desiguesedcats', to: 'static_pages#desiguesedcats'
  get 'contact', to: 'static_pages#contact'
  get 'help', to: 'static_pages#help'
  get 'privacypolicy', to: 'static_pages#privacypolicy'

  get "up" => "rails/health#show", as: :rails_health_check


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord

    belongs_to :user
    has_many :cart_items
    has_many :items, through: :cart_items



end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :cart


   
end

app/models/item.rb
class Item < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :price, numericality: { greater_than: 0, less_than: 1000 }, presence: true
    validates :image_url, presence: true

    
    has_many :cart_items, dependent: :destroy
    has_many :carts, through: :cart_items

    has_many :order_items
    has_many :orders, through: :order_items

end

app/models/order.rb
class Order < ApplicationRecord
 after_create :order_send

  belongs_to :user
  has_many :order_items
  has_many :items, through: :order_items

  def order_send
    UserMailer.order_email(self).deliver_now
    AdminMailer.order_email(self).deliver_now
  end

  def total
    total = 0
    self.items.each do |item|
      total += item.price
    end
    return total
  end

  def self.total_commande
    total = 0
    Order.all.each do |order|
      total += order.total 
    end
    return total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart, dependent: :destroy
  has_many :orders
  
  after_create :welcome_send, :create_cart

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  def first_name
    self[:first_name]
  end
  def last_name
    self[:last_name]
  end

  def create_cart
    Cart.create(user: self)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = Cart.all
  end

  def show
  @all_cart_items = CartItem.where(cart: current_user.cart)

  @cart = current_user.cart
  end

  
  def destroy
  end
  
  def create
  end

  def update
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    @total = params[:total].to_d
    # @event_id = params[:event_id]
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: 'eur',
            unit_amount: (@total*100).to_i,
            product_data: {
              name: 'Rails Stripe Checkout',
            },
          },
          quantity: 1
        },
        # metadata: {
        #   event_id: @event_id
        # },
      ],
      mode: 'payment',
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    redirect_to @session.url, allow_other_host: true
  end

  def success
    @total= CartItem.where(cart: current_user.cart).sum(&:price).to_f
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)

    order = Order.new(user: current_user)
    
    if order.save
      all_cart_items = CartItem.where(cart: current_user.cart)
      all_cart_items.each do |cart_item|
        OrderItem.create(item: cart_item.item, order: order)
        cart_item.destroy
      end
    end
  end
  
  def cancel
  end
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
      @items = Item.all
    end

    def show
      @item = Item.find(params[:id])
      @image_url = params[:image_url]
    end



end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def create
    # Before the rescue, at the beginning of the method
@stripe_amount = 500
begin
  customer = Stripe::Customer.create({
  email: params[:stripeEmail],
  source: params[:stripeToken],
  })
  charge = Stripe::Charge.create({
  customer: customer.id,
  amount: @stripe_amount,
  description: "Achat d'un produit",
  currency: 'eur',
  })
rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_order_path
end
# After the rescue, if the payment succeeded
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user), notice: "Votre compte a été créé avec succès."
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    
    @user = current_user
    
  end
  

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user), notice: "Votre compte a été créé avec succès."
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/orders/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/orders/new.html.erb
<style>
* {
  box-sizing: border-box;
}
 

.shopping-cart {
  width: 750px;
  height: 423px;
  margin: 80px auto;
  background: #e8b4f447;;
  box-shadow: 1px 2px 3px 0px rgba(0,0,0,0.10);
  border-radius: 6px;
  border: solid #58111A;
 
  display: flex;
  flex-direction: column;
}

.title {
  height: 60px;
  border-bottom: 1px solid #E1E8EE;
  padding: 20px 30px;
  color: #5E6977;
  font-size: 18px;
  font-weight: 400;
}
 
.item {
  padding: 20px 30px;
  height: 120px;
  display: flex;
}
 
.item:nth-child(3) {
  border-top:  1px solid #E1E8EE;
  border-bottom:  1px solid #E1E8EE;
}

.buttons {
  position: relative;
  padding-top: 30px;
  margin-right: 60px;
}
.delete-btn,
.like-btn {
  display: inline-block;
  Cursor: pointer;
}
.delete-btn {
  width: 18px;
  height: 17px;
  background: url(&amp;quot;delete-icn.svg&amp;quot;) no-repeat center;
}
 
.like-btn {
  position: absolute;
  top: 9px;
  left: 15px;
  background: url('twitter-heart.png');
  width: 60px;
  height: 60px;
  background-size: 2900%;
  background-repeat: no-repeat;
}

.is-active {
  animation-name: animate;
  animation-duration: .8s;
  animation-iteration-count: 1;
  animation-timing-function: steps(28);
  animation-fill-mode: forwards;
}
 
@keyframes animate {
  0%   { background-position: left;  }
  50%  { background-position: right; }
  100% { background-position: right; }
}

.image {
  margin-right: 50px;
  max-width: 100px; 
}

.image img {
  width: 100%; /* Assurez-vous que l'image remplit la largeur maximale spécifiée */
  height: auto; 
}

 

.description {
  padding-top: 10px;
  margin-right: 60px;
  width: 115px;
}
 
.description span {
  display: block;
  font-size: 14px;
  color: #43484D;
  font-weight: 400;
}
 
.description span:first-child {
  margin-bottom: 5px;
}
.description span:last-child {
  font-weight: 300;
  margin-top: 8px;
  color: #86939E;
}

.quantity {
  padding-top: 20px;
  margin-right: 60px;
}
.quantity input {
  -webkit-appearance: none;
  border: none;
  text-align: center;
  width: 32px;
  font-size: 16px;
  color: #43484D;
  font-weight: 300;
}
 

buttton[class*=bttn] {
  width: 30px;
  height: 30px;
  background-color: #E1E8EE;
  border-radius: 6px;
  border: none;
  cursor: pointer;
}


.minus-btn img {
  margin-bottom: 3px;
}
.plus-btn img {
  margin-top: 2px;
}
 
button:focus,
input:focus {
  outline:0;
}

.total-price {
  width: 83px;
  padding-top: 27px;
  text-align: center;
  font-size: 16px;
  color: #43484D;
  font-weight: 300;
}

@media (max-width: 800px) {
  .shopping-cart {
    width: 100%;
    height: auto;
    overflow: hidden;
  }
  .item {
    height: auto;
    flex-wrap: wrap;
    justify-content: center;
  }
  .image img {
    width: 50%;
  }
  .image,
  .quantity,
  .description {
    width: 100%;
    text-align: center;
    margin: 6px 0;
  }
  .buttons {
    margin-right: 20px;
  }
}


@font-face {
  font-family: 'Catboo';
  src: url('Catboo.ttf') format('truetype');
}

h1 {
  text-align: center;
  margin-bottom: 7%;
  font-family: 'Catboo', sans-serif; /* Utilisez le nom de la police correct */
  color: #58111A;
}

</style> 



<h1><center> Cart</center> </h1> 


    <div class="shopping-cart">
 
 
  <!-- Product #1 -->
  <div class="item">
    <div class="butttons">
      <span class="delete-btnt"></span>
      <span class="like-bttn"></span>
    </div>
 
    <div class="image">
    <%= image_tag "cat.jpeg", alt: "Description de l'image" %>

    </div>
 
    <div class="description">
      <span>Common Projects</span>
      <span>Bball High</span>
      <span>White</span>
    </div>
 
    <div class="quantity">
      <buttton class="plus-bttn" type="button" name="button">
        <img src="plus.svg" alt="" />
      </buttton>
      <input type="text" name="name" value="1">
      <buttton class="minus-btn" type="button" name="buttton">
        <img src="minus.svg" alt="" />
      </buttton>
    </div>
 
    <div class="total-price">$549</div>
  </div>
 
  <!-- Product #2 -->
  <div class="item">
    <div class="butttons">
      <span class="delete-bttn"></span>
      <span class="like-bttn"></span>
    </div>
 
    <div class="image">
    <%= image_tag "cat.jpeg", alt: "Description de l'image" %>
    </div>
 
    <div class="description">
      <span>Maison Margiela</span>
      <span>Future Sneakers</span>
      <span>White</span>
    </div>
 
    <div class="quantity">
      <buttton class="plus-bttn" type="buttton" name="buttton">
        <img src="plus.svg" alt="" />
      </buttton>
      <input type="text" name="name" value="1">
      <buttton class="minus-btn" type="buttton" name="buttton">
        <img src="minus.svg" alt="" />
      </buttton>
    </div>
 
    <div class="total-price">$870</div>
  </div>
 
  <!-- Product #3 -->
  <div class="item">
    <div class="butttons">
      <span class="delete-bttn"></span>
      <span class="like-bttn"></span>
    </div>
 
    <div class="image">
    <%= image_tag "cat.jpeg", alt: "Description de l'image" %>
    </div>
 
    <div class="description">
      <span>Our Legacy</span>
      <span>Brushed Scarf</span>
      <span>Brown</span>
    </div>
 
    <div class="quantity">
      <buttton class="plus-btn" type="buttton" name="buttton">
        <img src="plus.svg" alt="" />
      </buttton>
      <input type="text" name="name" value="1">
      <buttton class="minus-btn" type="buttton" name="buttton">
        <img src="minus.svg" alt="" />
      </buttton>
    </div>
 
    <div class="total-price">$349</div>
  </div>
  <div class="total-amount">
  <h2>Total: $1768</h2> <!-- Example total amount, replace with actual total -->
  <%= form_tag orders_path do %>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-description="Total Amount"
        data-amount="176800"
        data-locale="auto">
    </script>
  <% end %>
</div>
</div>
</div>


<script> 

$('.like-btn').on('click', function() {
   $(this).toggleClass('is-active');
});

</script> 