config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  
  resources :items

  devise_for :users

  resources :carts
  resources :users
  resources :orders
  resources :cart_items, only: [:create, :destroy]


  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end

  get 'team', to: 'static_pages#team'
  get 'uglycats', to: 'static_pages#uglycats'
  get 'fatcats', to:  'static_pages#fatcats'
  get 'desiguesedcats', to: 'static_pages#desiguesedcats'
  get 'contact', to: 'static_pages#contact'
  get 'help', to: 'static_pages#help'
  get 'privacypolicy', to: 'static_pages#privacypolicy'

  get "up" => "rails/health#show", as: :rails_health_check


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord

    belongs_to :user
    has_many :cart_items
    has_many :items, through: :cart_items



end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :cart


   
end

app/models/item.rb
class Item < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :price, numericality: { greater_than: 0, less_than: 1000 }, presence: true
    validates :image_url, presence: true

    
    has_many :cart_items, dependent: :destroy
    has_many :carts, through: :cart_items

    has_many :order_items
    has_many :orders, through: :order_items

end

app/models/order.rb
class Order < ApplicationRecord
 after_create :order_send

  belongs_to :user
  has_many :order_items
  has_many :items, through: :order_items

  def order_send
    UserMailer.order_email(self).deliver_now
    AdminMailer.order_email(self).deliver_now
  end

  def total
    total = 0
    self.items.each do |item|
      total += item.price
    end
    return total
  end

  def self.total_commande
    total = 0
    Order.all.each do |order|
      total += order.total 
    end
    return total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart, dependent: :destroy
  has_many :orders
  
  after_create :welcome_send, :create_cart

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  def first_name
    self[:first_name]
  end
  def last_name
    self[:last_name]
  end

  def create_cart
    Cart.create(user: self)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create
    item = Item.find(params[:item])
    puts '00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
    puts item
    @CartItem = CartItem.create(cart: current_user.cart, price: item.price, item: item)

    respond_to do |format|
      if @CartItem.save
        format.html { redirect_back fallback_location: root_path, notice: "Item was successfuly added to yout cart." }
        format.json { render :show, status: :created, location: @CartItem }
      end
    end
  end
    
  def update
  end
      
  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy

    redirect_to cart_item_path
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = Cart.all
  end

  def show
  @all_cart_items = CartItem.where(cart: current_user.cart)

  @cart = current_user.cart
  end

  
  def destroy
  end
  
  def create
  end

  def update
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    @total = params[:total].to_d
    # @event_id = params[:event_id]
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: 'eur',
            unit_amount: (@total*100).to_i,
            product_data: {
              name: 'Rails Stripe Checkout',
            },
          },
          quantity: 1
        },
        # metadata: {
        #   event_id: @event_id
        # },
      ],
      mode: 'payment',
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    redirect_to @session.url, allow_other_host: true
  end

  def success
    @total= CartItem.where(cart: current_user.cart).sum(&:price).to_f
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)

    order = Order.new(user: current_user)
    
    if order.save
      all_cart_items = CartItem.where(cart: current_user.cart)
      all_cart_items.each do |cart_item|
        OrderItem.create(item: cart_item.item, order: order)
        cart_item.destroy
      end
    end
  end
  
  def cancel
  end
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
      @items = Item.all
    end

    def show
      @item = Item.find(params[:id])
      @image_url = params[:image_url]
    end



end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def create
    # Before the rescue, at the beginning of the method
@stripe_amount = 500
begin
  customer = Stripe::Customer.create({
  email: params[:stripeEmail],
  source: params[:stripeToken],
  })
  charge = Stripe::Charge.create({
  customer: customer.id,
  amount: @stripe_amount,
  description: "Achat d'un produit",
  currency: 'eur',
  })
rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_order_path
end
# After the rescue, if the payment succeeded
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user), notice: "Votre compte a été créé avec succès."
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    
    @user = current_user
    
  end
  

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user), notice: "Votre compte a été créé avec succès."
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/index.html.erb
coucou

app/views/carts/show.html.erb
<style> 
.btn_red {
    color: red;
}

</style>
<% if @all_cart_items.present? %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card my-3">
          <div class="card-body">
            <% @all_cart_items.each do |cart_item| %>
              <div class="row align-items-center">
                <div class="col-2">
                  <%= image_tag cart_item.item.image_url, alt: cart_item.item.title, class: "img-fluid" %>
                </div>
                <div class="col-5">
                  <h4><%= cart_item.item.title %></h4>
                  <p><%= cart_item.item.description %></p> 
                </div>
                <div class="col-2">
                  <p>Prix: <%= cart_item.item.price %> € </p>
                  <p>Quantité: 1</p>
                </div>
                <div class="col-3">
                
                  <%= button_to "Delete", cart_item_path(cart_item), method: :delete, class: "btn_bot btn_red" %>

                </div>
              </div>
              <hr class="my-2"> 
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <p>Votre panier est vide.</p>
      </div>
    </div>
  </div>
<% end %>



<h3>Total: <%= @all_cart_items.sum(&:price) %>$</h3>

<%= button_to "Pay", checkout_create_path(total: @all_cart_items.sum(&:price)), class: "btn btn-primary", data: {turbo: false} %>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>

app/views/user/_form.html.erb
<%= form_with(model: user, local: true, method: :put) do |form| %>
  <div class="form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First name" %>
  </div>

  <div class="form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last name" %>
  </div>

  <div class="form-group">
    <%= form.emailt_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="actions text-center">
    <%= form.submit %>
  </div>
<% end %>

app/views/user/edit.html.erb
<main class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <h1>Editer votre profil</h1>

            <%= render 'form', user: @user %>
            <div class="text-center">
                <%= link_to 'Voir le profil', @user, class:"btn btn-warning" %> |
                <%= link_to '« Retour Accueil', root_path, class:"btn btn-outline-warning" %>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</main>

app/views/users/_form.html.erb
<style> 

.container {
  margin-top: 20px;
 
}

.table td {
  
 text-align: left;
  background-color:  #ff70b759;
  border-color:  #ff70b759;
  border-radius: 15px;

  .text-center {
  text-align: center;
 }

 
.form-control {
  width: 100%;
  font-size: 16px;
  border-radius: 5px;
  }


.btnn-primary {
  background-color:  #8AB9F1;
  color: #fff;
  padding: 10px 20px;
  border: none;
  border-radius: 5px;
 }



</style>



<div class="container">
  <table class="table">
   <td class="form-group">
          <%= form_with(model: user, local: true, method: :put) do |form| %>
            <%= form.email_field :email, class:"form-control", placeholder:"Email" %>
             <br>
             <br>

            <div class="text-center">
              <%= form.submit "Modifier", class: "btnn btnn-primary" %>
            </div>
          <% end %>
        </td>
     </table>
</div>

app/views/users/edit.html.erb
<style> 
.btnn-warning {
  background-color: #EAB4F8;
  color: #fff;
  padding: 10px 20px;
  text-decoration: none;
  border-radius: 5px;
}
.btnn-outline-warning {
    background-color: #EAB4F8;
    color: #fff;
    padding: 10px 10px;
    text-decoration: none;
    border-radius: 5px;
}

</style>


<main class="containner">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <center><h1>Editer votre profil</h1></center>
             <br>
             <br>

            <%= render 'form', user: @user %>
            <br>
            <br>

            <div class="text-center">
                <%= link_to 'See profile', user_path , class:"btnn btnn-warning" %>

                <% if current_user.is_admin %>
                  <%= link_to '« My Items', admin_items_path, class:"btnn btnn-outline-warning" %>
                <% else %>
                  <%= link_to '« Home', root_path, class:"btnn btnn-outline-warning" %>
                <% end %>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</main>

app/views/users/show.html.erb
  <style>
  .rounded-circle-container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100% ; 
  }
  
  .rounded-circle {
    width: 200px;
    height: 200px;
  }
  
  h1 {
    font-family: 'Catboo', sans-serif;
    color: #58111A;
  }
  @font-face {
  font-family: 'Catboo';
  src: url('Catboo.ttf') format('truetype');
}


.card {
  background-color: #ff70b759 !important;
  border: solid #FF70B8 2px;
}


.card-text {
  color: #58111A !important;
}


.text-danger {
  color: #ff0000; 
}

  
</style>

<div class="rounded-circle-container">
  <div class="rounded-circle overflow-hidden border border-dark d-inline-block">
    <%= image_tag("cat.jpeg", class: "img-fluid") %>
  </div>
</div>
<br>

<center><h1>Your profile</h1></center>

<center><p> <strong> Email:</strong> <%= @user.email %> </p></center>

<% if current_user.is_admin %>
 <center> <%= link_to 'My items', admin_items_path, class:"btn btn-outline-warning" %></center>
<% end %>
<br>


<center><%= link_to 'Edit profile', edit_user_path, class:"btn btn-outline-warning" %></center>

<br> 
<br>
<center><h2>Dashboard</h2></center>
<div class="container">
  <div class="card my-3 mx-auto text-center" style="max-width: 600px;">
   

    <div id="collapseOne" class="collapse hide" aria-labelledby="headingOne" data-parent="#accordionExample">
      <% if Order.all.length == 0 %>
        <p> No order </p>
      <% else %>
        <% Order.all.each do |order| %>
          <div class="card m-1">
            <div class="card-body">
              <p class="card-text">Order of : <%= order.created_at.strftime("%d.%m.%Y à %H:%M") %> de <%= order.user.email%></p>
              <p class="card-text"><small class="text-muted">Number of items : <%= order.items.length %></small></p>
              <p class="card-text"><small class="text-muted">Total : <%= order.total %> €</small></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="card m-2">
      <div class="card-body">
        <% if Order.all.length == 0 %>
          <h5 class="text-danger"><%= Order.all.length %> made orders.</h5>
        <% elsif Order.all.length == 1%>
         <h5 class="text-danger"><%= Order.all.length %> order. Total : <%= Order.total_commande %> $</h5>
        <% else %>
          <h5 class="text-danger"><%= Order.all.length %> orders. Total : <%= Order.total_commande %> $</h5>
        <% end %>
      </div>
    </div>

    <div class="card">
      <div class="card-header" id="headingTwo">
        <a class="font-weight-bold my-4 mb-0">
          <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" id="dashboard-text">
            All users
          </button>
        </a>
      </div>

      <div id="collapseTwo" class="collapse hide" aria-labelledby="headingTwo" data-parent="#accordionExample">
        <% User.all.each do |user| %>
          <div class="card m-1">
            <div class="card-body">
              <p class="card-text">Mail : <%= user.email %> created <%= user.created_at.strftime("%d.%m.%Y à %H:%M") %></p>
              <p class="card-text"><small class="text-muted">Number of orders : <%= user.orders.length %></small></p>
              <p class="card-text"><small class="text-muted">Total spent : <span class="text-danger"><%= user.orders.total_commande %> $</span></small></span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>