config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  
  resources :items

  devise_for :users

  resources :carts
  resources :users
  resources :orders
  resources :cart_items, only: [:create, :destroy]


  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end

  get 'team', to: 'static_pages#team'
  get 'uglycats', to: 'static_pages#uglycats'
  get 'fatcats', to:  'static_pages#fatcats'
  get 'desiguesedcats', to: 'static_pages#desiguesedcats'
  get 'contact', to: 'static_pages#contact'
  get 'help', to: 'static_pages#help'
  get 'privacypolicy', to: 'static_pages#privacypolicy'

  get "up" => "rails/health#show", as: :rails_health_check


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord

    belongs_to :user
    has_many :cart_items
    has_many :items, through: :cart_items



end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :cart


   
end

app/models/item.rb
class Item < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :price, numericality: { greater_than: 0, less_than: 1000 }, presence: true
    validates :image_url, presence: true

    
    has_many :cart_items, dependent: :destroy
    has_many :carts, through: :cart_items

    has_many :order_items
    has_many :orders, through: :order_items

end

app/models/order.rb
class Order < ApplicationRecord
 after_create :order_send

  belongs_to :user
  has_many :order_items
  has_many :items, through: :order_items

  def order_send
    UserMailer.order_email(self).deliver_now
    AdminMailer.order_email(self).deliver_now
  end

  def total
    total = 0
    self.items.each do |item|
      total += item.price
    end
    return total
  end

  def self.total_commande
    total = 0
    Order.all.each do |order|
      total += order.total 
    end
    return total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart, dependent: :destroy
  has_many :orders
  
  after_create :welcome_send, :create_cart

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  def first_name
    self[:first_name]
  end
  def last_name
    self[:last_name]
  end

  def create_cart
    Cart.create(user: self)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authorized?

  def index
    @items = Item.all
  end
  
  def show 
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def new
    @items = Item.all
    @item = Item.new
  end
  
  def create
    @item = Item.new(title: params[:title], description: params[:description], price: params[:price], image_url: params[:image_url])
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end
  
  def update
    @item = Item.find(params[:id])
    item_params =  params.require(:item).permit(:title, :description, :price, :image_url)
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end
  
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end
  
  
  private 
    def authorized?
      if current_user.is_admin == true
        return true
      else
        redirect_to root_path
      end
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = Cart.all
  end

  def show
  @all_cart_items = CartItem.where(cart: current_user.cart)

  @cart = current_user.cart
  end

  
  def destroy
  end
  
  def create
  end

  def update
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    @total = params[:total].to_d
    # @event_id = params[:event_id]
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: 'eur',
            unit_amount: (@total*100).to_i,
            product_data: {
              name: 'Rails Stripe Checkout',
            },
          },
          quantity: 1
        },
        # metadata: {
        #   event_id: @event_id
        # },
      ],
      mode: 'payment',
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    redirect_to @session.url, allow_other_host: true
  end

  def success
    @total= CartItem.where(cart: current_user.cart).sum(&:price).to_f
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)

    order = Order.new(user: current_user)
    
    if order.save
      all_cart_items = CartItem.where(cart: current_user.cart)
      all_cart_items.each do |cart_item|
        OrderItem.create(item: cart_item.item, order: order)
        cart_item.destroy
      end
    end
  end
  
  def cancel
  end
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
      @items = Item.all
    end

    def show
      @item = Item.find(params[:id])
      @image_url = params[:image_url]
    end



end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def create
    # Before the rescue, at the beginning of the method
@stripe_amount = 500
begin
  customer = Stripe::Customer.create({
  email: params[:stripeEmail],
  source: params[:stripeToken],
  })
  charge = Stripe::Charge.create({
  customer: customer.id,
  amount: @stripe_amount,
  description: "Achat d'un produit",
  currency: 'eur',
  })
rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_order_path
end
# After the rescue, if the payment succeeded
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user), notice: "Votre compte a été créé avec succès."
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    
    @user = current_user
    
  end
  

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user), notice: "Votre compte a été créé avec succès."
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/items/_form.html.erb
<%= form_with(model: [:admin, @item], local: true, method: :put) do |form| %>

  <div class="form-group mb-3 mt-3 col-sm">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group mb-3 mt-3 col-sm">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control" %>
  </div>

  <div class="form-group mb-3 mt-3 col-sm">
    <%= form.label :price %>
    <%= form.text_field :price, class:"form-control" %>
  </div>
  
  <div class="form-group mb-3 mt-3 col-sm">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, class:"form-control" %>
  </div>

  <div class="actions text-center">
    <%= form.submit 'Update', :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/admin/items/_form_new.html.erb
<%= form_tag url_for(action: 'create'), method: "post" do %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">


  <div class="form-group mb-3 mt-3 col-sm">
    <%= label_tag 'Title' %>
    <%= text_field_tag 'title', @item.title, class:"form-control" %>
  </div>

  <div class="form-group mb-3 mt-3 col-sm">
    <%= label_tag 'Description' %>
    <%= text_area_tag 'description', @item.description, class:"form-control" %>
  </div>

  <div class="form-group mb-3 mt-3 col-sm">
    <%= label_tag 'Price' %>
    <%= text_field_tag 'price', @item.price, class:"form-control" %>
  </div>
  
  <div class="form-group mb-3 mt-3 col-sm">
    <%= label_tag "Url de l'image" %>
    <%= text_field_tag 'image_url', @item.image_url, class:"form-control" %>
  </div>

  <div class="actions text-center">
    <%= submit_tag "Add item", class:"btn btn-success mt-3"%>
  </div>
<% end %>

app/views/admin/items/edit.html.erb
<main class="container mt-5">
  <div class="card my-3 text-center w-50 card-center">
      <h3 class="action-banner card-header">Modify</h3>
        <%= render 'form', item: @item %>
      <div class="text-center mb-3">
        <%= link_to 'Home', admin_items_path, class:"btn btn-outline-secondary" %>
      </div>
  </div>  
</main>

app/views/admin/items/index.html.erb
<style>
.card-index {
  background-color: #ff70b759;
  border: solid #FF70B8 2px!important;
  border-radius: 15px;

}

.card-index h4  { 
  color: #58111A;
}

.card-index p  { 
  color: #58111A;
}

.card-img-top {
  display: block;
  margin-left: auto;
  margin-right: auto;
}


.card-img-top {
  max-width: 100%;
  height: auto;
}



</style>


<main class="container">
  <div class="row row-cols-4 row-cols-md-3 col-sm-12 p-md-0 m-md-0 d-flex justify-content-center">

  <% @items.each do |item| %>
    <div class="col-sm-12 col-12 col-md-4">
        <div class="card border-secondary mb-4 card-index">
          <div class="card-header p-0">
            <%= image_tag item.image_url,  :size => "400x500", :crop => :fill, class: "card-img-top" %>
          </div>
          <div class="card-body">
            <h4 class="card-title"><%= item.title %></h4>
            <p class="card-text"><%= item.description %></p>
            <p class="card-text"><%= item.price %> $</p>
          </div>
          <div class="card-footer">
            <%= link_to "See more", admin_item_path(item.id), class:"btn" %>
          </div>
        </div>
      </a>
    </div>
  <% end %>
    <div class="col-sm-12 col-12 col-md-4">
      <a href="<%= new_admin_item_path %>" class="card-clic">
        <div class="card border-secondary mb-4 card-index">
          <div class="card-body">
            <i class="far fa-plus-square text-center mt-3 mr-2 card-img-top" style="font-size: 100px; color: black"></i>
            <h4 class="card-title"> </h4>
            <p class="card-text"> </p>
            <p class="card-text"> </p>
          </div>
          <div class="card-footer text-center">
            <%= link_to "Add new item", new_admin_item_path, class:"btn btn-success-dark mx-1 my-1" %>
          </div>
        </div>
      </a>
    </div>
</main>

app/views/admin/items/new.html.erb
<main class="container mt-5">
  <div class="card my-3 text-center w-50 card-center">
    <h3 class="action-banner card-header">Add new item</h3>
    <%= render 'form_new', item: @item  %>
  </div>
  <div class="text-center">
    <%= link_to 'Home', admin_items_path, class:"btn btn-outline-secondary" %>
  </div>
</main>

app/views/admin/items/show.html.erb
<style> 


.img-show {
  border-radius: 50px;
  overflow: hidden;
  height: 300px;
  width: 300px;
  display: flex;
  justify-content: center;
  margin: 0 auto; 
}


.img-show img {
  max-width: 100%; 
  height: auto; 
}


.card {
  margin-top: 20px; 
  padding: 20px; 
  margin-right: 10px; 
  height: 200px;
  width: 300px;
  display: flex; 
  justify-content: center; 
  margin: 0 auto; 
  background-color: #ff70b759;
}


.button_center {
  margin-right: 10px; 
}

.d-flex {
  justify-content: center;
  
}

</style>




<main class="container mb-5 mt-5">
  <div class="img-show mr-5">
    <%= image_tag @item.image_url, height: "500px;" %>
  </div>
  <br>
  <br>
  

  <div class="card">
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><strong>Title : </strong><%= @item.title %></li>
      <li class="list-group-item"><strong>Description : </strong><%= @item.description %></li>
      <li class="list-group-item"><strong>Prix : </strong><%= @item.price %> €</li>
    </ul>
  </div>


  <div class="d-flex justify-content-left">
  <%= link_to "Modify", edit_admin_item_path(@item.id), class: "btn btn-info button_center mr-2 mt-3" %>
  <%= form_with(model: [:admin, @item], local: true, url: admin_item_path, method: "delete") do |form| %>
    <%= form.submit "Delete", class: "btn btn-success mt-3" %>
  <% end %>
</div>

app/views/items/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <section class="hero-index">
      <div class="container my-5">
        <div class="row">
          <div class="col-lg-6">
            <img class="w-100 shadow" src="https://plus.unsplash.com/premium_photo-1707353402057-c95bdddb5b39?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" />
          </div>
          <div class="col-lg-6">
            <div class="p-5 mt-4">
                <h1 class="display-4">WELCOME</h1>
                <p class="lead">Dive into an unbelievable experience by purchasing cat pictures on our website.</p>
                <p class="lead"> Our curated collection captures the essence of feline charm, turning each image into a visual masterpiece.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="cards-index">
      <h1 class="h1-index display-4"> OUR ITEMS </h1>

      <div class="row row-cols-1 row-cols-md-4 g-4">
        <% @items.each do |item| %>
          <div class="col-index">
            <div class="card-index h-100">
              <img src="<%= item.image_url %>" class="card-img-top" alt="Cat">
              <%= link_to item_path(item, image_url:'') do %>
                 <button class="btn-index">View</button>
              <% end %>
            </div> 
          </div>
        <% end %>
      </div>
    </section>

    <section class="comments-index">
      <h1 class="h1-index display-4"> OUR CUSTOMERS CAT-ISFACTION </h1> <br>

      <div class="container">
        <div class="row">
          <div class="shadow-index">
            <div class="col-sm-12 col-index">
              <div class="col-sm-2">
                <img src="https://plus.unsplash.com/premium_photo-1677252438450-b779a923b0f6?q=80&w=2960&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="img-circle" width="60px">
              </div>
              <div class="col-sm-8 sm-index">
                <h4>First Name Last Name</h4>
                <p>Comment content</p>
              </div>
              <div class="col-sm-2 star-index">
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
              </div>
            </div>
            <hr class="hr-index">

            <div class="col-sm-12 col-index">
              <div class="col-sm-2">
                <img src="https://plus.unsplash.com/premium_photo-1677252438450-b779a923b0f6?q=80&w=2960&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="img-circle" width="60px">
              </div>
              <div class="col-sm-8 sm-index">
                <h4>First Name Last Name</h4>
                <p>Comment content</p>
              </div>
              <div class="col-sm-2 star-index">
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
              </div>
            </div>
            <hr class="hr-index">

            <div class="col-sm-12 col-index">
              <div class="col-sm-2">
                <img src="https://plus.unsplash.com/premium_photo-1677252438450-b779a923b0f6?q=80&w=2960&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="img-circle" width="60px">
              </div>
              <div class="col-sm-8 sm-index">
                <h4>First Name Last Name</h4>
                <p>Comment content</p>
              </div>
              <div class="col-sm-2 star-index">
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-regular fa-star"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/items/show.html.erb
<h1 class="h1_center"> <%= @item.title %> </h1>

<div class="card_show">
    <%= image_tag @item.image_url, alt: @item.title, class: "img-show" %>
        <div class="infos-show">
            <div class="border_show">
                <p>
                    <%= @item.description %>
                </p>
            </div>

            <div class="price_show">
                <p>
                   <%= @item.price %> $ 
                </p>

                <p>
                   ID - <%= @item.id %>
                </p>
            </div> <br>

            <select class="form-select" aria-label="Default select example">
              <option selected>Choose quantity</option>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
            </select> <br>
            
            <select class="form-select" aria-label="Default select example">
              <option selected>Choose size</option>
              <option value="1">A3</option>
              <option value="2">A4</option>
              <option value="3">A5</option>
            </select> <br>

            <div class="truck">
              <i class="fa-solid fa-truck-fast"></i>
              <p> Delivery in 1 to 3 working days </p>
            </div>

            <div class="box">
              <i class="fa-solid fa-box"></i>
              <p> Free delivery from 70$ </p>
            </div>

            <div class="btn-show">
              <% if user_signed_in? %>
                <%= button_to "Add to cart", cart_items_path, method: :post, params: { item: @item }, class: "btn_bot" %>
              <% else %>
                <%= link_to "Login to add", new_user_session_path, class: "btn_bot" %>
              <% end %>
                <i class="fa-regular fa-heart"></i>
                <i class="fa-solid fa-heart"></i>
            </div>
</div>          
          

        
</div>