config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  
  resources :items

  devise_for :users

  resources :carts
  resources :users
  resources :orders
  resources :cart_items, only: [:create, :destroy]


  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end

  get 'team', to: 'static_pages#team'
  get 'uglycats', to: 'static_pages#uglycats'
  get 'fatcats', to:  'static_pages#fatcats'
  get 'desiguesedcats', to: 'static_pages#desiguesedcats'
  get 'contact', to: 'static_pages#contact'
  get 'help', to: 'static_pages#help'
  get 'privacypolicy', to: 'static_pages#privacypolicy'

  get "up" => "rails/health#show", as: :rails_health_check


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord

    belongs_to :user
    has_many :cart_items
    has_many :items, through: :cart_items



end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :cart


   
end

app/models/item.rb
class Item < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :price, numericality: { greater_than: 0, less_than: 1000 }, presence: true
    validates :image_url, presence: true

    
    has_many :cart_items, dependent: :destroy
    has_many :carts, through: :cart_items

    has_many :order_items
    has_many :orders, through: :order_items

end

app/models/order.rb
class Order < ApplicationRecord
 after_create :order_send

  belongs_to :user
  has_many :order_items
  has_many :items, through: :order_items

  def order_send
    UserMailer.order_email(self).deliver_now
    AdminMailer.order_email(self).deliver_now
  end

  def total
    total = 0
    self.items.each do |item|
      total += item.price
    end
    return total
  end

  def self.total_commande
    total = 0
    Order.all.each do |order|
      total += order.total 
    end
    return total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart, dependent: :destroy
  has_many :orders
  
  after_create :welcome_send, :create_cart

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  def first_name
    self[:first_name]
  end
  def last_name
    self[:last_name]
  end

  def create_cart
    Cart.create(user: self)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = Cart.all
  end

  def show
  @all_cart_items = CartItem.where(cart: current_user.cart)

  @cart = current_user.cart
  end

  
  def destroy
  end
  
  def create
  end

  def update
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
      @items = Item.all
    end

    def show
      @item = Item.find(params[:id])
      @image_url = params[:image_url]
    end



end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user), notice: "Votre compte a été créé avec succès."
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chapatte</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://fonts.cdnfonts.com/css/times-new-romance" rel="stylesheet">
    <script src="https://kit.fontawesome.com/99977e05a9.js" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/"></script>      

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <nav class="navbar navbar-expand-lg navbar-light bg-pink">
    <div class="container-fluid">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="<%= root_path %>">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Pictures
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="/uglycats">Ugly Cats</a></li>
                        <li><a class="dropdown-item" href="/desiguesedcats">Desiguised Cats</a></li>
                       <li><a class="dropdown-item" href="/fatcats">Fat Cats</a></li>
                    </ul>
                </li>
            </ul>
        </div>


        <div class="navbar-brand ">
            <img class="logo" src="CHPT.png" alt="Logo">
        </div>

        <% if user_signed_in? %>
          <div class="basket-container">
              <%= link_to "<i class='fa-solid fa-bag-shopping'></i> #{current_user.cart.items.count}".html_safe, cart_path(current_user.id), class:"nav-link btn"%>
          </div>
        <% else %>
          <%= link_to ('<i class="fa-solid fa-bag-shopping"></i>').html_safe, new_user_session_path %>
        <% end %>

        <% if user_signed_in? %>
          <div class="btn-group">
            <button class="btn btn-outline-dark btn-lg btn-pink dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if current_user.is_admin %>
              My Admin profile
            <% else %>
              My profile
            <% end %>
            </button>

            <ul class="dropdown-menu">
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, data: {turbo_method: :delete} %>
              </li>

              <li> 
                <% if current_user.is_admin %>
                  <%= link_to "My Admin profile", user_path(current_user) %>
                <% else %>
                  <%= link_to "My Profile", user_path(current_user) %>
                <% end %>
              </li>
            
              <li>
                <%= link_to "Edit email / password", edit_user_registration_path %>
              </li>
            </ul>
          </div>

        <% else %>

          <div class="btn-group">
            <button class="btn btn-outline-dark btn-lg btn-pink dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Login
            </button>

            <ul class="dropdown-menu">
              <li>    
                <%= link_to "Log in", new_user_session_path %>
              </li>
      
              <li>
                <%= link_to "Sign up", new_user_registration_path %>
              </li>
            </ul>
          </div>
      <% end %>
    </div>
  </nav>

  
<%= yield %>

 
<footer class="mainfooter" role="contentinfo">
  <div class="footer-middle">
    <div class="container">
      <div class="row text-center"> 
        <div class="col-md-2 col-sm-6">
        <div class="footer-pad">
        <h4><a class="foot-link" href="/team">Company</a></h4>
      </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="footer-pad">
          <h4><a class="foot-link" href="/contact">Contact</a></h4>
          </div>
        </div>
        <div class="col-md-3">
        <div class="social-links">
          <%= link_to "https://instagram.com", target: "_blank", class: "social-link" do %>
            <%= image_tag "instagram.png", width: "30", height: "30" %>
          <% end %>
          <%= link_to "https://facebook.com", target: "_blank", class: "social-link" do %>
            <%= image_tag "facebook.png", width: "30", height: "30" %>
          <% end %>
          <%= link_to "https://twitter.com", target: "_blank", class: "social-link" do %>
            <%= image_tag "twitter.png", width: "30", height: "30" %>
          <% end %>
        </div>
      </div>
       
        <div class="col-md-2 col-sm-6"> 
          <div class="footer-pad">
          <h4><a class="foot-link" href="/help">Help</a></h4>
          </div>
        </div>
        <div class="col-md-2 col-sm-6"> 
          <div class="footer-pad">
          <h4><a class="foot-link" href="/privacypolicy">Privacy Policy</a></h4>
          </div>
        </div>
      </div>
      
      <div class="row">
      <div class="col-md-12 copy text-center mx-auto">
     
        <p>&copy; Copyright 2024 - Chapatte. All rights reserved.</p>
      </div>
    </div>
    
</footer>


</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>